AWSTemplateFormatVersion: 2010-09-09

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./api.yml
      StageName: prod
      Variables:
        LambdaFunctionName: !Ref ParseEventFromUrlFunction

  ParseEventFromUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambda-modules/lambda.backend/target/function.zip
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: provided
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
      Events:
        ProxyEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /{proxy+}
            Method: ANY

  ParseEventFromUrlFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ParseEventFromUrlFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*

Outputs:
  LambdaEndpoint:
    Description: API Gateway URL of the Lambda Function
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod/"